#!/bin/bash



VIRTUAL_DISK="$HOME/virtual_disk.img"
MOUNT_POINT="$HOME/mount_point"




dd if=/dev/zero of="$VIRTUAL_DISK" bs=1M count=1024




mkfs.ext4 "$VIRTUAL_DISK"




mkdir -p "$MOUNT_POINT"




sudo mount -o loop "$VIRTUAL_DISK" "$MOUNT_POINT"




sudo chmod -R 777 "$MOUNT_POINT"




mkdir -p "$MOUNT_POINT/log"




mkdir -p "$HOME/backup"




echo "Виртуальный диск смонтирован в $MOUNT_POINT. Папка 'log' создана."




function generate_files() 
{
    local files_counter=$1
    local target_dir=$2
    if [ -d "$target_dir" ]; then
        echo "Генерация файлов по 25 Мб для теста: $files_counter шт."
        for i in $(seq 1 "$files_counter"); do
            dd if=/dev/zero of="$target_dir/file_$i" bs=1M count=25 status=none
            sleep 0.1
        done
    fi
} 




function testcase()
{
    local LOG_DIR=$1
    local BACKUP_DIR=$2
    local THRESHOLD=$3
    local N=$4
    local FILES_COUNTER=$5
    echo "Начало теста. Порог: $THRESHOLD%, удалению подлежат файлы: $N шт."
    generate_files "$FILES_COUNTER" "$LOG_DIR"
    ./archieve_script.sh "$LOG_DIR" "$BACKUP_DIR" "$THRESHOLD" "$N"
    rm -rf "$LOG_DIR"/*

    if [ -d "$BACKUP_DIR" ]; then
        rm -rf "$BACKUP_DIR"/*
    else 
        LAST_DIR=$(basename "$$BACKUP_DIR")
        BACKUP_DIR="$HOME/$LAST_DIR"
        rm -rf "$BACKUP_DIR"/*
    fi
    echo "Тест завершён."
}



#тест 1. порог - 50%, удаляем 10 файлов, создаём 30 файлов по 25 мб (750 мб)
testcase "$MOUNT_POINT/log" "$HOME/backup" 50 10 30



#тест 2. порог - 50%, удаляем 10 файлов, создаём 10 файлов по 25 мб (250 мб), 
testcase "$MOUNT_POINT/log" "$HOME/backup" 50 10 10



#тест 3. порог - 50%, удаляем 10 файлов, создаём 30 файлов по 25 мб (250 мб), директория backup_dir не существует
testcase "$MOUNT_POINT/log" "$HOME/backup1" 50 10 30



#тест 4. порог - 50%, удаляем 10 файлов, создаём 30 файлов по 25 мб (250 мб), директория log_dir не существует
testcase "$MOUNT_POINT/log1" "$HOME/backup" 50 10 30



# Размонтируем виртуальный диск
sudo umount "$MOUNT_POINT"



# Удаляем точку монтирования
rmdir "$MOUNT_POINT"



# Удаляем файл виртуального диска
rm -f "$VIRTUAL_DISK"



echo "Виртуальный диск размонтирован, папка удалена, файл диска удалён."
